DROP TABLE IF EXISTS SKILL;

CREATE TABLE SKILL (
  id INT(10)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS PROJECT;

CREATE TABLE PROJECT (
  id INT(10)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  id INT(10)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);
